# version: "3"

services:

  db:
    container_name: "postgresRestDB"
    image: postgres:13-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  backend:
    container_name: "RestTutorial"
    build:
      context: .


    command: >
      sh -c "
            python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000
            "
    expose:
      - 8000
    ports:
      - "8000:8000"

    env_file:
      - ./.env
    volumes:
      - static:/static
      - aws:/aws
      - ./RestTutorial/:/RestTutorial




volumes:
  frontend_build: {}
  static: {}
  aws: {}